<a href="https://colab.research.google.com/github/sanjay-sj87/computer_vision/blob/main/MNIST_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch
from torchvision import datasets, transforms
import torch.nn as nn
import torch.optim as optim

In [35]:
# Preprocess the data: convert to float and normalize
xx = xx.float() / 255.0

In [19]:
# Update the dataset with the preprocessed data
dataset = TensorDataset(xx, yy)
data = DataLoader(dataset, batch_size=32, shuffle=True)

# Check the updated batch shape and type
for batch in data:
    print(f"Batch data shape: {batch[0].shape}, dtype: {batch[0].dtype}")
    print(f"Batch labels shape: {batch[1].shape}, dtype: {batch[1].dtype}")
    break

Batch data shape: torch.Size([32, 28, 28]), dtype: torch.float32
Batch labels shape: torch.Size([32]), dtype: torch.int64


Now, let's define a simple class-based neural network model for classification.

In [20]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(28 * 28, 128)  # Input: 28x28 images
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, len(selected_classes)) # Output: number of selected classes

    def forward(self, x):
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x

model = SimpleNN()
print(model)

SimpleNN(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=3, bias=True)
)


Next, we'll define the loss function, optimizer, and implement the training and testing loops.

In [21]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train_model(model, dataloader, criterion, optimizer, epochs=5):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for inputs, labels in dataloader:
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"Epoch {epoch+1}, Loss: {running_loss/len(dataloader):.4f}")

def test_model(model, dataloader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, labels in dataloader:
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    print(f"Accuracy on the test set: {accuracy:.2f}%")

# Train the model
train_model(model, data, criterion, optimizer, epochs=10)

# Test the model (using the same data for simplicity, but in a real scenario, you'd have a separate test set)
test_model(model, data)

Epoch 1, Loss: 0.9419
Epoch 2, Loss: 0.4894
Epoch 3, Loss: 0.1848
Epoch 4, Loss: 0.1035
Epoch 5, Loss: 0.0786
Epoch 6, Loss: 0.0464
Epoch 7, Loss: 0.0309
Epoch 8, Loss: 0.0221
Epoch 9, Loss: 0.0144
Epoch 10, Loss: 0.0104
Accuracy on the test set: 100.00%


In [22]:
dataset = datasets.MNIST(root='./data', train=True, download=True,
                         transform=transforms.ToTensor())

In [23]:
x_train = dataset.data
y_train = dataset.targets

In [24]:
selected_classes = [0, 1, 2]

In [25]:
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    print(indices)

tensor([   1,   21,   34,   37,   51,   56,   63,   68,   69,   75,   81,   88,
          95,  108,  114,  118,  119,  121,  156,  169,  192,  206,  209,  210,
         216,  229,  232,  234,  246,  249,  260,  283,  293,  296,  303,  320,
         326,  359,  399,  427,  429,  435,  440,  451,  453,  458,  462,  464,
         473,  489,  519,  524,  526,  527,  542,  577,  582,  596,  603,  612,
         633,  639,  656,  662,  666,  667,  668,  669,  689,  702,  709,  712,
         733,  743,  745,  776,  781,  787,  790,  818,  825,  849,  859,  860,
         869,  872,  889,  903,  927,  943,  949,  952,  957,  965,  979,  984,
         997, 1000, 1015, 1018])
tensor([  3,   6,   8,  14,  23,  24,  40,  59,  67,  70,  72,  77,  78,  99,
        102, 104, 105, 112, 113, 124, 128, 134, 152, 174, 177, 184, 200, 201,
        205, 208, 211, 224, 231, 248, 251, 269, 270, 276, 290, 309, 310, 315,
        345, 351, 355, 357, 358, 366, 382, 394, 397, 398, 406, 408, 416, 443,
        447, 45

In [36]:
x_final, y_final = [], []
for cls in selected_classes:
    indices = (y_train == cls).nonzero(as_tuple=True)[0][:100]
    x_final.append(x_train[indices])
    y_final.append(y_train[indices])

In [27]:
len(x_final)

3

In [28]:
xx = torch.cat(x_final)
yy = torch.cat(y_final)

In [29]:
yy

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [30]:
from torch.utils.data import TensorDataset, DataLoader

In [31]:
dataset = TensorDataset(xx, yy)

In [32]:
data = DataLoader(dataset, batch_size=32, shuffle=True)

In [33]:
for batch in data:
    print(batch[0].shape)
    break

torch.Size([32, 28, 28])
